### ISSUE TITLE
1. Fixing driver error

### ISSUE THREAD

**Issue by ThijmenStaatsen** [FabianDumitrascu/DroneDelivery#21]
### 1. Title:
Fixing driver error

### 2. Description:

- **Objective**: Everyone being able to use Gazebo in the docker environment.

- **Acceptance Criteria**: Error is fixed and we can all use Gazebo in the docker environment

- **Steps to Reproduce**: n.v.t.

- **Screenshots/Logs**: 

- **Dependencies**: Whole project

- **Notes**:

**Comment by FabianDumitrascu** [comment]
Did not complete issue, moving onwards with wrong drivers
